configs {
  key: "chainercv.py2.chainer-stable"
  value {
    requirement {
      cpu: 8
      memory: 48
      gpu: 2
      disk: 8
    }
    command: "sh .chainerci/tests.sh"
    environment_variables {
      key: "PYTHON"
      value: "2"
    }
    environment_variables {
      key: "CHAINER"
      value: "5.2.0"
    }
  }
}

configs {
  key: "chainercv.py3.chainer-stable"
  value {
    requirement {
      cpu: 8
      memory: 48
      gpu: 2
      disk: 8
    }
    command: "sh .chainerci/tests.sh"
    environment_variables {
      key: "PYTHON"
      value: "3"
    }
    environment_variables {
      key: "CHAINER"
      value: "5.2.0"
    }
  }
}

configs {
  key: "chainercv.py2.chainer-latest"
  value {
    requirement {
      cpu: 8
      memory: 48
      gpu: 2
      disk: 8
    }
    command: "sh .chainerci/tests.sh"
    environment_variables {
      key: "PYTHON"
      value: "2"
    }
    environment_variables {
      key: "CHAINER"
      value: "6.0.0b2"
    }
  }
}

configs {
  key: "chainercv.py3.chainer-latest"
  value {
    requirement {
      cpu: 8
      memory: 48
      gpu: 2
      disk: 8
    }
    command: "sh .chainerci/tests.sh"
    environment_variables {
      key: "PYTHON"
      value: "3"
    }
    environment_variables {
      key: "CHAINER"
      value: "6.0.0b2"
    }
  }
}
